name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cpp@v2
        with:
          cmake-version: '3.16.3'

      - name: Configure CMake
        run: cmake .

      - name: Build
        run: cmake --build .

      - name: Run Tests
        run: make run_tests