name: Run Tests

on:
  push:
    branches:
      - main
      - working

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up CMake
        run: sudo apt-get install -y cmake
  
      - name: Configure
        run: cmake .
  
      - name: Build
        run: cmake --build .
  
      - name: Run Tests
        run: allTests  