name: Run Tests

on:
  push:
    branches:
      - main
      - working

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up C++ environment
        uses: actions/setup-cpp@v2
        with:
          repository: actions/setup-cpp
          version: v2
          compiler: clang
          cpp-version: '9.4'

      - name: Build project
        run: cmake . && cmake --build .

      - name: Run tests
        run: ./allTests